### ISSUE TITLE
Detailed setup/configuration steps missing

### ISSUE THREAD

**Issue by SAPSentinel** [sivadhulipala1999/SheetSimplify_with_RAG#1]
Please expand the Readme with clear steps. After executing pip install . , not clear how to run this application.

**Comment by sivadhulipala1999** [comment]
@SAPSentinel thanks for the feedback. If you are still not sure about how to run the files, this is what I meant. 

- Run the llm.py file to directly execute the chat function from the command line 
- Run the streamlit_app.py file to execute the chat function with the streamlit frontend in place 

Hope this helps!
